### ISSUE TITLE
Visitor Story: Project show page without login

### ISSUE THREAD

**Issue by Robbie-Smith** [Robbie-Smith/kickstarter_clone#10]
As a visitor when I visit /projects/:username/:project_name
I should be able to view that project
And I should see a link to support the project
And I should see how many supporters of the project there is
And I should see how many days are left in the project
And I should see how much money is currently pledged, in the form of a progress bar

**Comment by drod1000** [comment]
@Dpalazzari @kheppenstall @jdconrad89 @Robbie-Smith  started working on this one and ran into an interesting issue. Since a project can be owned by multiple people how do you guys think we should deal with this in the routes? Should we make it so that either of their names will render the same view, should we use both in the route, pick one, or only use the project name?

**Comment by Robbie-Smith** [comment]
I've been thinking about the routes issue as well, I think that is something we all need to talk about and decide on together. Let's chat about it tomorrow.

**Comment by Dpalazzari** [comment]
example, @drod1000 ?
